[env:demo_panel]
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino

; ── Paměť / flash ─────────────────────────────────────────────────────────────
board_build.arduino.memory_type = opi_opi
board_build.f_flash             = 80000000L
board_build.f_cpu               = 240000000L
board_build.partitions          = large_spiffs_16MB.csv
board_upload.flash_size         = 16MB

; ── Kompilujeme všechny cpp soubory v src a hry ────────────────
build_src_filter = +<*.cpp> +<hry/*.cpp>

; ── Build flagy ────────────────────────────────────────────────────────────────
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; ── Závislosti ─────────────────────────────────────────────────────────────────
lib_deps =
    ; --- Senzory ---
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit LSM6DS @ ^4.7.3          ; LSM6DS3 – jako v examples/lsm6ds3_gyroscope
    pololu/VL53L0X @ ^1.3.1
    adafruit/Adafruit TCS34725 @ ^1.4.4

    ; --- Displeje ---
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.4  ; ST7789 – jako v examples/2.8_tft_display
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit BusIO @ ^1.16.1
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4

    ; --- LED pásky ---
    adafruit/Adafruit NeoPixel @ ^1.12.3
    fastled/FastLED @ ^3.7.0

; ── Monitor a Upload ──────────────────────────────────────────────────────────── 
upload_port     = /dev/ttyUSB0
upload_speed    = 115200
monitor_speed   = 115200
monitor_filters = esp32_exception_decoder